version: 2
jobs:
  build:
    working_directory: ~/bimobject/bim-select
    docker:
      - image: circleci/node:6-browsers
        environment:
          CHROME_BIN: "/usr/bin/chrome"
    steps:
      - checkout
      - restore_cache:
          key: yarn-cache-{{ .Branch }}
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}

      - run: yarn install

      - save_cache:
          key: yarn-cache-{{ .Branch }}
          paths:
            - ~/.cache/yarn
      - save_cache:
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - node_modules

      - run: yarn run test

# vim: sw=2 ts=2 expandtab
